OperationSquid/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + patterns(
    '',
    # Examples:
    # url(r'^$', 'OperationSquid.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^user/', include("user_account.urls", namespace="user")),
    url(r'^external/', include('social.apps.django_app.urls', namespace='social')),
    url(r'^live/', include('sharing.urls', namespace='live')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^overseer/', include('overseer.urls', namespace="overseer")),
    url(r'^', include("events.urls", namespace="events")),
)

events/urls.py
from django.conf.urls import url, patterns

import views

urlpatterns = patterns(
    '',
    url(r'^event/(?P<event_id>\d+)/attend/', views.AttendEventView.as_view(), name="attend"),
    url(r'^event/(?P<event_id>\d+)/', views.EventView.as_view(), name="event"),
    url(r'^event/', views.NewEventView.as_view(), name="new"),
    url(r'^', views.IndexView.as_view(), name="index"),
)

overseer/urls.py
from django.conf.urls import url, patterns

import views
urlpatterns = patterns(
    '',
    url(r'^(?P<event_id>\d+)/create/appointment/', views.AppointmentView.as_view(), name="createAppointment"),
    url(r'^(?P<event_id>\d+)/create/news/', views.NewsView.as_view(), name="createNews"),
    url(r'^(?P<event_id>\d+)/', views.IndexView.as_view(), name="index"),
    url(r'^', views.AllView.as_view(), name="index_general"),

)

overseer/forms.py
from django import forms

from sharing.models import News, Appointment

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

class NewsForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(NewsForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper(self)

        self.helper.layout.append(Submit('save', "Save"))
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-sm-3'
        self.helper.field_class = 'col-sm-9'

    class Meta:
        model = News
        exclude = ("related_event",)

class AppointmentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(AppointmentForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper(self)

        self.helper.layout.append(Submit('save', "Save"))
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-sm-3'
        self.helper.field_class = 'col-sm-9'

    class Meta:
        model = Appointment
        exclude = ("related_event",)

overseer/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import View
from forms import NewsForm, AppointmentForm

from events.models import Event
# Create your views here.
class IndexView(View):
    def get(self, request, event_id=0):
        context = {}

        context['news_form'] = NewsForm()
        context['event'] = get_object_or_404(Event, id=event_id)

        return render(request, "overseer/index.html", context)

class AllView(View):
    def get(self,request):

        context  = {}

        context['events'] = Event.objects.all()

        return render(request, "overseer/all.html", context)

class NewsView(View):
    def get(self, request, event_id):
        context = {}

        context['news_form'] = NewsForm()

        return render(request, "overseer/createNews.html", context)

    def post(self, request, event_id):
        form = NewsForm(request.POST)

        if form.is_valid():
            model = form.save(commit=False)

            model.related_event = get_object_or_404(Event, id=event_id)

            model.save()

            return redirect("overseer:index", event_id)
        else:
            context = {}

            context['news_form'] = form
            context['event'] = get_object_or_404(Event, id=event_id)

            return render(request, "overseer/createNews.html", context)

class AppointmentView(View):
    def get(self, request, event_id):
        context = {}

        context['appointment_form'] = AppointmentForm()

        return render(request, "overseer/createAppointment.html", context)

    def post(self, request, event_id):
        form = AppointmentForm(request.POST)

        if form.is_valid():
            model = form.save(commit=False)

            model.related_event = get_object_or_404(Event, id=event_id)

            model.save()

            return redirect("overseer:index", event_id)
        else:
            context = {}

            context['appointment_form'] = form
            context['event'] = get_object_or_404(Event, id=event_id)

            return render(request, "overseer/createAppointment.html", context)

statics/templates/overseer/all.html
{% extends 'base.html' %}

{% block content %}

		<div class="row">
			<div class="col-sm-12">
				<h1 class="page-header">Overseer</h1>
			</div>
			<div class="col-sm-8">
				<ul class="list-group">
					{% for event in events %}

						<a href="{% url 'overseer:index' event.id %}" ><li class="list-group-item list-group-item-{{ event.GetOpenStatus }}">{{ event.name }}</li></a>
					{% endfor %}

				</ul>
			</div>
		<div class="col-sm-4">
			<a href="{% url 'events:new'%}" class="btn btn-primary btn-block">Create new event</a>
		</div>
		</div>
{% endblock %}

statics/templates/overseer/createAppointment.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
	<div class="row">
		<div class="col-md-12">
			<h2>Create new Appointment</h2>
			{%  crispy appointment_form %}
		</div>
	</div>
{% endblock %}

statics/templates/overseer/createNews.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
	<div class="row">
		<div class="col-md-12">
			<h2>Create new news object</h2>
			{%  crispy news_form %}
		</div>
	</div>
{% endblock %}

statics/templates/overseer/index.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
	<div class="row">
		<div class="col-md-3">
			<h2><a href="{% url 'overseer:createNews' event.id %}" class="btn btn-danger btn-lg btn-block">Create
				news</a></h2>
		</div>

		<div class="col-md-3">
		<h2><a href="{% url 'overseer:createAppointment' event.id %}" class="btn btn-warning btn-lg btn-block">Create an event</a></h2>
		</div>
	</div>
	</div>
{% endblock %}