OperationSquid/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + patterns(
    '',
    # Examples:
    # url(r'^$', 'OperationSquid.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^user/', include("user_account.urls", namespace="user")),
    url(r'^external/', include('social.apps.django_app.urls', namespace='social')),
    url(r'^live/', include('sharing.urls', namespace='live')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^overseer/', include('overseer.urls', namespace="overseer")),
    url(r'^', include("events.urls", namespace="events")),
)

events/urls.py
from django.conf.urls import url, patterns

import views

urlpatterns = patterns(
    '',
    url(r'^event/(?P<event_id>\d+)/attend/', views.AttendEventView.as_view(), name="attend"),
    url(r'^event/(?P<event_id>\d+)/', views.EventView.as_view(), name="event"),
    url(r'^event/', views.NewEventView.as_view(), name="new"),
    url(r'^', views.IndexView.as_view(), name="index"),
)

events/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.utils.timezone import datetime

# Create your models here.
class Event(models.Model):
    name = models.CharField(max_length=30)
    location = models.TextField()
    description = models.TextField()

    registration_open = models.BooleanField(default=False)
    event_date = models.DateTimeField()

    def __str__(self):
        return self.name

    def GetAllAttendees(self):
        return Registration.objects.filter(related_event=self)

    def GetAllConfirmedAttendees(self):
        return self.GetAllAttendees().filter(paid=True)

    def GetAllPendingAttendees(self):
        return self.GetAllAttendees().filter(paid=False)

    def GetOpenTag(self):
        if self.event_date.date() == datetime.now().date():
            return "success"
        elif self.event_date.date() > datetime.now().date():
            return "primary"
        else:
            return "warning"

    class Meta:
        ordering = ["-event_date"]


class Registration(models.Model):
    related_event = models.ForeignKey(Event)
    related_user = models.ForeignKey(User)

    date_created = models.DateTimeField(auto_now_add=True, name="date_registered", verbose_name="Date Registered")

    paid = models.BooleanField(default=False)
    date_paid = models.DateTimeField(null=True)

    def __str__(self):
        return "%s registered for %s" % (self.related_user.get_full_name(), self.related_event.name)


class Access(models.Model):
    related_registration = models.ForeignKey(Registration)

    date_created = models.DateTimeField(auto_now_add=True, name="date_entered", verbose_name="Date Entered")


class Payment(models.Model):
    related_registration = models.ForeignKey(Registration)

    date_created = models.DateTimeField(auto_now_add=True, name="data_paid", verbose_name="Date Paid")

    def __str__(self):
        return self.related_registration.related_event.name


@receiver(pre_save, sender=Payment)
def SetRegistrationAsSaved(sender, instance=None, **kwargs):
    if instance is not None:
        instance.related_registration.paid = True
        instance.related_registration.save()

events/forms.py
from crispy_forms.helper import FormHelper
from django import forms
from crispy_forms.layout import Submit

from .models import Event


class EventForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper(self)

        self.helper.layout.append(Submit('save', 'save'))

        self.helper.form_class = 'form-horizontal'

        self.helper.label_class = 'col-sm-3'
        self.helper.field_class = 'col-sm-9'

    class Meta:
        model = Event
        exclude = ()

events/views.py
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views.generic import View
from django.shortcuts import get_object_or_404, redirect
from django.contrib import messages
from  django.contrib.auth.decorators import login_required

import forms
from .models import *

# Create your views here.
class IndexView(View):
    def get(self, request):
        context = {}

        context['events_open'] = Event.objects.filter(registration_open=True)
        return render(request, "events/index.html", context)


class EventView(View):
    def get(self, request, event_id):
        context = {}

        context['event_specified'] = get_object_or_404(Event, pk=event_id)
        try:
            context['registration'] = Registration.objects.get(related_event__id=event_id, related_user=request.user)
        except:
            pass

        return render(request, "events/event.html", context)


class AttendEventView(View):
    @method_decorator(login_required())
    def get(self, request, event_id):
        event = get_object_or_404(Event, pk=event_id)

        obj, created = Registration.objects.get_or_create(related_event=event, related_user=request.user)

        obj.save()

        return redirect("events:event", event_id)


class NewEventView(View):
    @method_decorator(login_required)
    def get(self, request):
        if request.user.privilege.level == 1:
            messages.warning(request, "You do not have the authority to access that page!")
            return redirect("events:index")

        context = {}

        context['event_form'] = forms.EventForm()

        return render(request, 'events/createEvent.html', context)

    @method_decorator(login_required)
    def post(self, request):
        if request.user.privilege.level == 1:
            messages.warning(request, "You do not have the authority to access that page!")
            return redirect("events:index")

        context = {}

        form = forms.EventForm(request.POST)
        if form.is_valid():
            form.clean()
            form.save()
            return redirect("events:index")
        else:
            context["event_form"] = form
            return render(request, 'events/createEvent.html', context)

statics/templates/events/createEvent.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="row">
<div class="col-md-12">
	<h1 class="page-header">Create a new event</h1>
	{% crispy event_form %}
</div>
</div>
{% endblock %}

statics/templates/events/event.html
{% extends 'base.html' %}

{% block content %}
	<div class="row">
		<div class="col-xs-12">
			<h1 class="page-header">{{ event_specified }}</h1>
		</div>
	</div>
	<div class="row">
		<div class="col-md-6">
			<p>{{ event_specified.description|escape }}</p>
			{% if registration %}
				<p class="btn btn-block btn-success">You are registered for this event!</p>
			{% else %}
			<a href="{% url "events:attend" event_specified.id %}" class="btn btn-block	 btn-primary">Attend this event!</a>
			{% endif %}
		</div>
		<div class="col-md-6 alert alert-info">
			<h2>Location</h2>
			{{ event_specified.location }}
		</div>
	</div>
	<div class="row">
		<div class="col-md-6">
			<h2>Confirmed Attendees</h2>

			<ul class="list-group">
				{% for attendee in event_specified.GetAllConfirmedAttendees %}
					<li class="list-group-item list-group-item-success">{{ attendee.related_user.get_full_name }}</li>
				{% endfor %}
			</ul>
		</div>
		<div class="col-md-6"><h2>Pending Attendees</h2>
			<ul class="list-group">
				{% for attendee in event_specified.GetAllPendingAttendees %}
					<li class="list-group-item list-group-item-warning">{{ attendee.related_user.get_full_name }}</li>
				{% endfor %}
			</ul>
		</div>
	</div>
{% endblock %}

statics/templates/events/index.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
<div class="col-xs-12"><h1 class="page-header">Open events</h1></div>
<div class="col-sm-12">
{% if user.privilege > 1 %}
<a class="btn btn-block btn-default" href="{% url 'events:new' %}">Create New Event</a>
	<div class="divider"></div>
{% endif %}
	<ul class="list-group">
		{% for event in events_open %}
			<li class="list-group-item"><p>{{ event }}<a href="{% url 'events:event' event.id %}" class="pull-right btn btn-primary">More info</a></p></li>
		{% endfor %}
	</ul>
</div>
</div>
{% endblock %}