OperationSquid/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + patterns(
    '',
    # Examples:
    # url(r'^$', 'OperationSquid.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^user/', include("user_account.urls", namespace="user")),
    url(r'^external/', include('social.apps.django_app.urls', namespace='social')),
    url(r'^live/', include('sharing.urls', namespace='live')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^overseer/', include('overseer.urls', namespace="overseer")),
    url(r'^', include("events.urls", namespace="events")),
)

events/urls.py
from django.conf.urls import url, patterns

import views

urlpatterns = patterns(
    '',
    url(r'^event/(?P<event_id>\d+)/attend/', views.AttendEventView.as_view(), name="attend"),
    url(r'^event/(?P<event_id>\d+)/', views.EventView.as_view(), name="event"),
    url(r'^event/', views.NewEventView.as_view(), name="new"),
    url(r'^', views.IndexView.as_view(), name="index"),
)

overseer/urls.py
from django.conf.urls import url, patterns

import views
urlpatterns = patterns(
    '',
    url(r'^(?P<event_id>\d+)/create/appointment/', views.AppointmentView.as_view(), name="createAppointment"),
    url(r'^(?P<event_id>\d+)/create/news/', views.NewsView.as_view(), name="createNews"),
    url(r'^(?P<event_id>\d+)/', views.IndexView.as_view(), name="index"),
    url(r'^', views.AllView.as_view(), name="index_general"),

)

user_account/urls.py
from django.conf.urls import url, patterns

import views

urlpatterns = patterns(
    '',
    url(r'^login/', views.LoginView.as_view(), name="login"),
    url(r'^logout/', views.LogoutView.as_view(), name="logout"),
    url(r'^(?P<username>\w+)/', views.UserPageView.as_view(), name="userpage"),
    url(r'^', views.IndexView.as_view(), name="index"),

)

statics/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head lang="en">
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, user-scalable=no">

	<title>Operation Squid - {{ title }}</title>
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
	<style>body {
		padding-top: 50px;
	}</style>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
					data-target="#navbar-collapsible">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="{% url 'events:index' %}">SME</a>
		</div>
		<div class="collapse navbar-collapse navbar-right" id="navbar-collapsible">
			<ul class="navbar-nav nav">
				<li><a href="{% url 'events:index' %}">Open Events</a></li>

				{% if user.is_authenticated %}
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Your events <span
								class="badge">{{ user_events_active|length }}</span></a>
						<ul class="dropdown-menu">
							{% if user_events_active %}
								{% for event in user_events_active %}
									<li class="bg-{{ event.related_event.GetOpenTag }}"><a
											href="{% url 'live:index' event.related_event.id %}">{{ event.related_event }}</a>
									</li>
								{% endfor %}
							{% else %}
								<li><p class="navbar-text">There's nothing!</p></li>
							{% endif %}
						</ul>
					</li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown"
						   role="button">Hi {{ user.first_name }} <span class="caret"></span> </a>
						<ul class="dropdown-menu">
							<li><a href="{% url 'user:index' %}">Your page</a></li>
							<li class="divider"></li>
							{% if user.privilege.level > 1 %}
								<li><a href="{% url 'overseer:index_general' %}">Overseer</a></li>
								{% if user.is_superuser %}
									<li><a href="{% url 'admin:index' %}">Admin</a></li>
								{% endif %}
								<li class="divider"></li>
							{% endif %}
							<li><a href="{% url 'user:logout' %}">Log out</a></li>
						</ul>
					</li>
				{% else %}
					<li><a href="{% url 'user:login' %}">Log in</a></li>
				{% endif %}
			</ul>
		</div>
	</div>
</nav>

<div class="container">
	<div class="row">
		{% if messages %}
			{% for message in messages %}
				<div class="alert alert-{{ message.tags }}">{{ message }}
					<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
							aria-hidden="true">&times;</span></button>
				</div>
			{% endfor %}
		{% endif %}
	</div>
	{% block content %}

	{% endblock %}
</div>
<div class="container-fluid">
	{% block content-full %}

	{% endblock %}
</div>

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>