OperationSquid/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + patterns(
    '',
    # Examples:
    # url(r'^$', 'OperationSquid.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^user/', include("user_account.urls", namespace="user")),
    url(r'^external/', include('social.apps.django_app.urls', namespace='social')),
    url(r'^live/', include('sharing.urls', namespace='live')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^overseer/', include('overseer.urls', namespace="overseer")),
    url(r'^', include("events.urls", namespace="events")),
)

events/urls.py
from django.conf.urls import url, patterns

import views

urlpatterns = patterns(
    '',
    url(r'^event/(?P<event_id>\d+)/attend/', views.AttendEventView.as_view(), name="attend"),
    url(r'^event/(?P<event_id>\d+)/', views.EventView.as_view(), name="event"),
    url(r'^event/', views.NewEventView.as_view(), name="new"),
    url(r'^', views.IndexView.as_view(), name="index"),
)

sharing/urls.py
from django.conf.urls import url, patterns

import views


urlpatterns = patterns(
    '',
    url(r'^(?P<event_id>\d+)/message/(?P<message_id>\d+)/', views.MessageView.as_view(), name="message"),
    url(r'^(?P<event_id>\d+)/message/new/', views.NewMessageView.as_view(), name="new_message"),
    url(r'^(?P<event_id>\d+)/', views.IndexView.as_view(), name="index"),
)

sharing/models.py
from django.db import models
from django.contrib.auth.models import User
from events.models import Event
from django.db.models.signals import pre_delete
from django.dispatch import receiver

# Create your models here.
class Message(models.Model):
    related_user = models.ForeignKey(User)
    related_event = models.ForeignKey(Event)
    related_message = models.ForeignKey('Message', null=True, blank=True)
    related_categories = models.ManyToManyField('Category')

    title = models.CharField(max_length=20)
    body = models.TextField(null=True)
    file= models.FileField(upload_to='documents/%Y/%m/%d/%H/%M/%S', null=True, blank=True)


    date_created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-date_created',)

    def __len__(self):
        return len(Comment.objects.filter(related_message=self))


class Comment(models.Model):
    related_message = models.ForeignKey(Message)
    related_user = models.ForeignKey(User)

    body = models.TextField()

    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.body

    class Meta:
        ordering = ("-date_created",)

class Appointment(models.Model):
    related_event = models.ForeignKey(Event)

    date = models.DateField()

    start_time = models.TimeField()
    end_time = models.TimeField()

    title = models.CharField(max_length=20)
    body = models.TextField()

    class Meta:
        ordering = ("date", "start_time")

class News(models.Model):
    related_event = models.ForeignKey(Event)

    date_posted = models.DateTimeField(auto_now_add=True)

    title = models.CharField(max_length=24)
    body = models.TextField()

    class Meta:
        ordering = ("-date_posted", )

class Category(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


@receiver(pre_delete, sender=Message)
def DeleteRelatedMedia(sender, instance=None, **kwargs):
    if instance is not None:
        instance.file.delete()

sharing/forms.py
from django import forms
from models import Message, Category, Comment
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

class MessageForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(MessageForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.layout.append(Submit('save', 'save'))
        self.helper.form_class = 'form-horizontal'

        self.helper.label_class = 'col-sm-3'
        self.helper.field_class = 'col-sm-9'

    class Meta:
        model = Message
        exclude = ('related_user', 'related_event', 'related_message')
        fields = ('title', 'body', 'file', 'related_categories')


class CommentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.helper= FormHelper(self)
        self.helper.layout.append(Submit('save', 'Comment'))
        self.helper.form_class = "form-horizontal"

        self.helper.label_class = 'hidden'
        self.helper.field_class = 'col-sm-12'

    class Meta:
        model = Comment
        exclude = ("related_user", "related_message")

sharing/views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import View
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from events.models import Event
from reservations.models import Item
import models
import forms

# Create your views here.
class IndexView(View):
    @method_decorator(login_required)
    def get(self, request, event_id):
        context = {}
        context['event'] = get_object_or_404(Event, pk=event_id)
        context['latest_messages'] = models.Message.objects.all()[:10]
        context['news'] = models.News.objects.filter(related_event =context['event'])
        context['agenda'] = models.Appointment.objects.filter(related_event=context['event'])[:5]
        context['items'] = Item.objects.filter(relatedEvent=context['event'])

        print context['news']
        return render(request, "sharing/index.html", context)

class NewMessageView(View):
    @method_decorator(login_required)
    def get(self, request, event_id):
        context = {}
        context['event'] = get_object_or_404(Event, pk=event_id)
        context['upload-form'] = forms.MessageForm()

        return render(request, "sharing/newMessage.html", context)

    @method_decorator(login_required)
    def post(self, request, event_id):
        form = forms.MessageForm(request.POST, request.FILES)

        if form.is_valid():
            model = form.save(commit=False)

            model.related_user = request.user
            model.related_event = get_object_or_404(Event, pk=event_id)

            form.save()
            messages.success(request, "Message posted succesfully")
            return redirect("live:index", event_id)
        else:
            context = {}
            context['upload-form'] = form
            return render(request, "sharing/newMessage.html", context)

class MessageView(View):
    @method_decorator(login_required)
    def get(self, request, event_id, message_id):
        context = {}

        context['comment_form'] = forms.CommentForm()
        context['event'] = get_object_or_404(Event, pk=event_id)
        context['message'] = get_object_or_404(models.Message, pk=message_id)
        context['comments'] = models.Comment.objects.filter(related_message=context['message'])


        return render(request, "sharing/message.html", context)
    def post(self, request, event_id, message_id):
        comment = forms.CommentForm(request.POST)

        if comment.is_valid():
            model = comment.save(commit=False)
            model.related_user = request.user
            model.related_message = get_object_or_404(models.Message, id=message_id)

            model.save()

            messages.success(request, "Succesfully posted your comment")
            return redirect("live:message", event_id, message_id)
        else:
            context =  {}
            context['comment_form'] = forms.CommentForm()
            context['event'] = get_object_or_404(Event, pk=event_id)
            context['message'] = get_object_or_404(models.Message, pk=message_id)

            return render(request, "sharing/message.html", context)

statics/templates/sharing/index.html
{% extends 'base.html' %}

{% block content-full %}
	<div class="row">
		<div class="col-md-9">
			<div class="row">
				<div class="col-sm-12">
					<div class="row">
						<div class="col-md-8">
							<div class="panel panel-primary">
								<div class="panel-heading">
									<h2 class="text-center">News</h2>
								</div>
								<div class="panel-body">
									{% for item in news %}
										<h1>{{ item.title }}</h1>
										<p>{{ item.body|truncatewords:20 }}</p>
									{% endfor %}
								</div>
							</div>
						</div>
						<div class="col-md-4">
							<div class="panel panel-success">
								<div class="panel-heading">
									<h2>Agenda</h2>
								</div>
								<div class="panel-body">
									{% for appointment in agenda %}
										<p>{{ appointment.title }} - {{ appointment.start_time }}
											to {{ appointment.end_time }}</p>
									{% endfor %}
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-sm-12">
					<div class="panel panel-info">
						<div class="panel-heading">
							<h2>Reserveren</h2>
						</div>
						<div class="panel-body">
							<div class="row">
								{% for item in items %}
									<div class="col-md-3 text-center">
										<h3>{{ item.name }}</h3>
										<img src="{{ item.image.url }}" class="img-responsive">

										<p>{{ item.description|truncatewords:6 }}</p>
									</div>

								{% endfor %}
							</div>
						</div>
					</div>

				</div>
			</div>
		</div>

		<div class="col-md-3">
			<div class="panel panel-warning">
				<div class="panel-heading">
					<h2>Messages - <a href="{% url 'live:new_message' event.id %}">New Message</a></h2>
				</div>
				<div class="panel-body">
					{% if latest_messages %}
						{% for message in latest_messages %}
							{% include 'snippets/sharing/message.html' %}
						{% endfor %}
					{% else %}
						<p>There's nothing here!</p>

					{% endif %}
				</div>
			</div>


		</div>
	</div>
{% endblock %}

statics/templates/sharing/message.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
	<div class="row">
		<div class="col-sm-12">
			{% include 'snippets/sharing/message.html' %}
		</div>
		<div class="row">
			<div class="col-md-9">
				{% for comment in comments %}
					<div class="well">
						<p>{{ comment.body }}</p>

						<p><strong>Posted by </strong> {{ comment.related_user.get_full_name }}
							<strong>on</strong> {{ comment.date_created|date }}</p>
					</div>
				{% endfor %}
			</div>
			<div class="col-md-3">
				<h3>Leave a comment</h3>
				{% crispy comment_form %}
			</div>
		</div>
	</div>
{% endblock %}

statics/templates/sharing/newMessage.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
	<div class="row">
<div class="col-md-12">
	<h2>Start a conversation</h2>
	{% crispy upload-form %}
</div>
</div>
{% endblock %}